apiVersion: v1
kind: Service
metadata:
  name: log-relay
  namespace: fhir
spec:
  type: ClusterIP
  selector:
    run: ci-build
  ports:
  - name: logrelay
    port: 4000
    targetPort: 4000
    protocol: TCP
